### ISSUE TITLE
Exception in plugin CodeSearch (1.0.0)

### ISSUE THREAD

**Issue by Aleksey-Voko** [guojianhua/code-search#1]
**In the new version (2020.1) of PyCharm:**
Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED
Current violators count: 1
[Stacktrace.txt](https://github.com/guojianhua/code-search/files/4464470/Stacktrace.txt)

**Comment by guojianhua** [comment]
Hello, thank you for your feedback. CodeSearch 1.1.0 has fixed the issue #1. Please upgrade it.
