### ISSUE TITLE
PHPStorm 2020.1.1 plugin exception

### ISSUE THREAD

**Issue by mihai-valentin** [guojianhua/code-search#2]
Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED

Current violators count: 1

[stacktrace.txt](https://github.com/guojianhua/code-search/files/4650075/stacktrace.txt)

**Comment by guojianhua** [comment]
Hello, thank you for your feedback. CodeSearch 1.1.0 has fixed the issue #2. Please upgrade it.

**Comment by mihai-valentin** [comment]
Thank You
